In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6])

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [5]:
print(a[0])

[1 2 3 4]


In [6]:
#zeros function
np.zeros(2)

array([0., 0.])

In [7]:
np.zeros(1)

array([0.])

In [8]:
#ones function
np.ones(2)

array([1., 1.])

In [9]:
np.empty(2)

array([1., 1.])

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [13]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
x=np.ones(2,dtype=np.int64)
x

array([1, 1], dtype=int64)

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [18]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [22]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [24]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [26]:
array_example.ndim

3

In [27]:
array_example.size

24

In [30]:
array_example.shape

(3, 2, 4)

In [32]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [33]:
b=a.reshape(3,2) #changing size
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [91]:
b.ravel() #makes 1d array

array([1, 2, 3, 4, 5, 6])

In [34]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [38]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [39]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [40]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [42]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [43]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [45]:
data = np.array([1, 2, 3])
data[1]

2

In [46]:
# indexing & slicing
data[0:2]

array([1, 2])

In [47]:
data[1:]

array([2, 3])

In [48]:
data[-2:]

array([2, 3])

In [49]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [50]:
print(a[a < 5])

[1 2 3 4]


In [51]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [52]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [53]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [92]:
c.min()

3

In [93]:
c.max()

10

In [94]:
c.sum()

52

In [54]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [55]:
# numpy vs lists: takes less memory space
import sys
l=range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [56]:
array = np.arange(1000)
print(array.size*array.itemsize)

4000


In [60]:
#numpy is fast and convenient
import time
SIZE=1000
l1=range(SIZE)
l2=range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

#python list
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("python list took", (time.time()-start)*1000)
#numpy array
result=a1+a2
print("numpy took ", (time.time()-start)*1000)

python list took 0.9903907775878906
numpy took  1.9924640655517578


In [61]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

In [62]:
a1+a2

array([5, 7, 9])

In [63]:
a2-a1

array([3, 3, 3])

In [64]:
a1*a2

array([ 4, 10, 18])

In [65]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [66]:
a1-a2

array([-3, -3, -3])

In [67]:
#ndim
a=np.array([5,6,7])
a[0]

5

In [68]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [69]:
a=np.array([5,6,7])
a.ndim

1

In [70]:
a.itemsize

4

In [71]:
a.dtype

dtype('int32')

In [97]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.int64)
a.itemsize

8

In [98]:
a

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [103]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [104]:
np.std(a)

1.707825127659933

In [99]:
a.sum(axis=0) #vertical sum

array([ 9, 12], dtype=int64)

In [100]:
a.sum(axis=1) #horizontal sum

array([ 3,  7, 11], dtype=int64)

In [76]:
a.size

6

In [77]:
a.shape #width, height

(3, 2)

In [80]:
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [82]:
l=range(5)
l

range(0, 5)

In [83]:
l[0]

0

In [84]:
l[1]

1

In [85]:
np.arange(1,5)

array([1, 2, 3, 4])

In [86]:
np.arange(1,5,2)

array([1, 3])

In [87]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [88]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [89]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [107]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[5,6],[7,8],[9,6]])

In [116]:
#iterate through arrays
for row in a:
    print(row)

[1 2]
[3 4]
[5 6]


In [117]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6


In [119]:
#sticking together two arrays
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [121]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [123]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [124]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [125]:
np.arange(30).reshape(2,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [108]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
b

array([[5, 6],
       [7, 8],
       [9, 6]])

In [110]:
a+b

array([[ 6,  8],
       [10, 12],
       [14, 12]])

In [111]:
a*b

array([[ 5, 12],
       [21, 32],
       [45, 36]])

In [112]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ],
       [0.55555556, 1.        ]])

In [114]:
n=[6,7,8]
n[0:2]

[6, 7]

In [115]:
n[-1]

8

# w3 schools

# creating arrays

In [127]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [128]:
#Use a tuple to create a NumPy array:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [129]:
#dimensions in arrays
#0-D arrays
import numpy as np

arr = np.array(42)

print(arr)

42


In [130]:
#1-D arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [131]:
#2-D arrays
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [132]:
#3-D arrays
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [133]:
#check number of dimensions
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [134]:
#higher dimensional arrays
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# numpy array indexing

In [141]:
import numpy as np

arr = np.array([1, 2, 3, 4])
#Get the first element from the following array:
print(arr[0])

#Get the second element from the following array.
print(arr[1])

#Get third and fourth elements from the following array and add them.
print(arr[2] + arr[3])

1
2
7


In [139]:
#access 2-d arrays
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

#Access the element on the first row, second column: 
print('2nd element on 1st row: ', arr[0, 1])

#Access the element on the 2nd row, 5th column:
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


In [142]:
#access 3-d arrays
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [143]:
#navigate indexing
#Print the last element from the 2nd dim:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# numpy array slicing

In [146]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
#Slice elements from index 1 to index 5
print(arr[1:5])

#Slice elements from index 4 to the end of the array:
print(arr[4:])

#Slice elements from the beginning to index 4 (not included):
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [149]:
#negative slicing
print(arr[-3:-1])

#Return every other element from index 1 to index 5:
print(arr[1:5:2])

#Return every other element from the entire array:
print(arr[::2])

[5 6]
[2 4]
[1 3 5 7]


In [152]:
#slicing 2-d array
#From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

#From both elements, return index 2:
print(arr[0:2, 2])

#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# numpy datatypes

In [153]:
#checking datatype of an array
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [154]:
#Creating Arrays With a Defined Data Type
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [155]:
#Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [156]:
#A non integer string like 'a' can not be converted to integer (will raise an error):
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [157]:
#Converting Data Type on Existing Arrays
#Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [158]:
#Change data type from float to integer by using int as parameter value:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [159]:
#Change data type from integer to boolean:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# NumPy Array Copy vs View

In [164]:
#Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

#Make a view, change the original array, and display both arrays:
y = arr.view()
arr[0] = 42

print(arr)
print(y)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [165]:
#Check if Array Owns its Data
#Print the value of the base attribute to check if an array owns it's data or not:
print(x.base)
print(y.base)

None
[42  2  3  4  5]


# numpy array shape

In [166]:
#Get the Shape of an Array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [167]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# NumPy Array Reshaping

In [168]:
#Reshape From 1-D to 2-D
#Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [169]:
#Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [170]:
#Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):
newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [172]:
#Check if the returned array is a copy or a view:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [173]:
#Convert 1D array with 8 elements to 3D array with 2x2 elements:
newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [174]:
#Flattening the arrays
#Convert the array into a 1D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# NumPy Array Iterating

In [175]:
#Iterate on the elements of the following 1-D array:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [176]:
#Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [177]:
#Iterate on each scalar element of the 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [178]:
#Iterate on the elements of the following 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [179]:
#Iterate down to the scalars:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [180]:
#Iterating Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [181]:
#Iterate through the array as a string:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [182]:
#Iterate through every scalar element of the 2D array skipping 1 element:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [183]:
#Enumerate on following 1D arrays elements:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [184]:
#Enumerate on following 2D array's elements:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# NumPy Joining Array

In [186]:
#join 2 arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

#join 2-d array
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [187]:
#joining arrays using stack function
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [190]:
#hstack() to stack along rows.
arr = np.hstack((arr1, arr2))
print(arr)

#vstack()  to stack along columns
arr = np.vstack((arr1, arr2))
print(arr)

#dstack() to stack along height, which is the same as depth.
arr = np.dstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array

In [191]:
#Split the array in 3 parts:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [192]:
#Split the array in 4 parts:
newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [193]:
#Access the splitted arrays:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [194]:
#Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [195]:
#Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [196]:
#Split the 2-D array into three 2-D arrays along rows.
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [197]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows
newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NumPy Searching Arrays

In [198]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [200]:
#Find the indexes where the values are even:
x = np.where(arr%2 == 0)
print(x)

#Find the indexes where the values are odd:
x = np.where(arr%2 == 1)

print(x)

(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)


In [201]:
#Find the indexes where the value 7 should be inserted:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [202]:
#Find the indexes where the value 7 should be inserted, starting from the right:
x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [203]:
#Find the indexes where the values 2, 4, and 6 should be inserted:
x = np.searchsorted(arr, [2, 4, 6])

print(x)

[0 0 0]


# NumPy Sorting Arrays

In [204]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [205]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [206]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [207]:
#sort 2-d array
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# NumPy Filter Array

In [208]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [209]:
#Creating the Filter Array
#Create a filter array that will return only values higher than 42:
# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [210]:
#filter even elements
# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True]
[42 44]


# Creating Filter Directly From Array

In [211]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [212]:
#Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [ ]:
y
